- name: Install systemd-timesyncd on Ubuntu-based systems
  package:
    name: systemd-timesyncd
    state: present

- name: Ensure systemd-timesyncd is enabled
  systemd:
    name: systemd-timesyncd
    enabled: true
    state: started

- name: Configure systemd-timesyncd
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    mode: '0644'
  notify: Restart timesyncd
