- name: Allow Bacula Storage Director
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port:  9103
    jump: ACCEPT
    state: present
    comment: "Allow Bacula Storage Director"
  when: configure_firewall | bool

- name: Allow Bacula Director
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 9101
    jump: ACCEPT
    state: present
    comment: "Allow Bacula Director"
  when: configure_firewall | bool

- name: Allow Bacula Client
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 9102
    jump: ACCEPT
    state: present
    comment: "Allow Bacula Client"
  when: configure_firewall | bool