- name: Allow group sysadmin passwordless sudo
  ansible.builtin.copy:
    dest: /etc/sudoers.d/sysadmin
    content: "%noc ALL=(ALL) NOPASSWD: ALL\n"
    owner: root
    group: root
    mode: '0440'
    validate: '/usr/sbin/visudo -cf %s'
