- name: Ensure required useful packages are installed
  ansible.builtin.package:
    name:
      - glances
      - iotop
      - qemu-guest-agent
      - net-tools
      - plocate
      - vim
      - git
    state: present