
- name: Install NGINX
  ansible.builtin.include_role:
    name: nginxinc.nginx_core.nginx

- name: Deploy NetBox reverse proxy config
  ansible.builtin.template:
    src: netbox_nginx.conf.j2
    dest: /etc/nginx/conf.d/netbox.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload NGINX
