- name: Allow TCP port 9000 for Portainer
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 9000
    jump: ACCEPT
    state: present
    comment: "Allow TCP for Portainer"
