- name: Allow Jenkins 443
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 443
    jump: ACCEPT
    state: present
    comment: "Allow Jenkins 443"
  when: configure_firewall | bool


- name: Allow Jenkins 80
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    jump: ACCEPT
    state: present
    comment: "Allow Jenkins 80"
  when: configure_firewall | bool