- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Reload NGINX
  ansible.builtin.systemd:
    name: nginx
    state: reloaded

- name: Restart Netbox
  ansible.builtin.systemd:
    name: netbox
    state: restarted

- name: Restart Netbox-RQ
  ansible.builtin.systemd:
    name: netbox-rq
    state: restarted